version: "3.9"

services:
  
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
    secrets:
      - mysql_user
      - mysql_pass
      - mysql_root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net_spring_app
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$(cat /run_secrets/mysql_root_pass) || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  # Servicio de la app de Spring con Java
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-app:1.0
    container_name: spring_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE} # dev, prod, qa  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    secrets:
      - mysql_user
      - mysql_pass
    networks:
      - net_spring_app
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  net_spring_app:
    name: net_spring_app

volumes:
  mysql_data:
    name: mysql_data

secrets:
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_pass:
    file: ./secrets/mysql_pass.txt
  mysql_root_pass:
    file: ./secrets/mysql_root_pass.txt

