# Configuraciones de arranque bases de mi spring app generales
# Siempre se carga
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# healtcheck
management.endpoints.web.exposure.include=health
# never -> nadie ve el detalle del healtcheck
# always -> cualquiera ve el healtch check
# when_authorized -> estás autenticado en tu app y tienes permisos en spring security (prod)
management.endpoint.health.show-details=always


